# -*- coding: utf-8 -*-
"""utils_me.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pdW5C30kOkZMQqo2A_E3ay64MbXqf_G_
"""

import pandas as pd
import re

def get_train_test_data(data_dir):

    train_data = pd.read_json(f"{data_dir}/train.json")
    test_data = pd.read_json(f"{data_dir}/test.json")

    train_data.drop(["id"], axis = 1, inplace = True)
    test_data.drop(["id"], axis = 1, inplace = True)

    return train_data, test_data

# Convert all text to lowercase
# Remove newlines and double spaces
# Add start of sentence and end of sentence tokens

def preprocess_util(input_data):

    lowercase = input_data.lower()

    removed_newlines = re.sub("\n|\r|\t", " ", lowercase)

    removed_double_spaces = re.sub("  ", " ", removed_newlines)

    s = "[SOS] " + removed_double_spaces + " [EOS]"

    return s

def preprocess(input_data):

    preprocess_summary = input_data["summary"].apply((lambda summary : preprocess_util(summary)))

    preprocess_dialogue = input_data["dialogue"].apply(lambda dialogue : preprocess_util(dialogue))

    return preprocess_summary, preprocess_dialogue

